# Generated by Django 5.0.3 on 2024-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
