# Generated by Django 5.0.3 on 2024-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_customer_phone_number_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
