# Generated by Django 5.0.3 on 2024-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_remove_emailconfirmation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
