# Generated by Django 5.0.3 on 2024-04-28 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_remove_customer_account_alter_account_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
