name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_EMAIL_BACKEND: ${{ secrets.DJANGO_EMAIL_BACKEND }}
      DJANGO_EMAIL_HOST: ${{ secrets.DJANGO_EMAIL_HOST }}
      DJANGO_EMAIL_PORT: ${{ secrets.DJANGO_EMAIL_PORT }}
      DJANGO_EMAIL_HOST_USER: ${{ secrets.DJANGO_EMAIL_HOST_USER }}
      DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
      DJANGO_EMAIL_USE_TLS: ${{ secrets.DJANGO_EMAIL_USE_TLS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create and Activate venv
      run: |
        python -m venv venv
        source venv/bin/activate
        pip list
      working-directory: backend/OnlineBanking/

    - name: Install poetry
      run: |
        source venv/bin/activate
        pip install poetry
      working-directory: backend/OnlineBanking/

    - name: Install dependencies
      run: |
        source venv/bin/activate
        poetry install
      working-directory: backend/OnlineBanking/

    - name: Run Django tests
      run: |
        source venv/bin/activate
        python manage.py test
      working-directory: backend/OnlineBanking/